# Generated by Django 4.1.5 on 2023-01-07 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_created_date_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 7, 7, 8, 27, 924166)),
        ),
    ]
